import express from "express";
import { McpServer, ResourceTemplate } from "@modelcontextprotocol/sdk/server/mcp.js";
import { SSEServerTransport } from "@modelcontextprotocol/sdk/server/sse.js";
import { z } from "zod";

const app = express();

const server = new McpServer({
  name: "example-server",
  version: "1.0.0"
}, {
  capabilities: {}
});

server.resource('get-user', 'user://{userID}', {}, (userID) => {
  return {
    name: "example-user",
    description: `User with ID ${userID}`,
    template: `<p>User ID: ${userID}</p>`,
    styles: ["p { color: blue; }"]
  };
})

server.prompt(
  "review-code",
  { code: z.string() },
  ({ code }) => ({
    messages: [{
      role: "user",
      content: {
        type: "text",
        text: `Please review this code:\n\n${code}`
      }
    }]
  })
);



server.registerTool('component', {
  description: `This tool accepts angular component code generated by the LLM and processes it. Eg. @Component({ ... })
  class ExampleComponent {
    constructor() { }
  }`,
  inputSchema: {
    type: "string",
    description: `Angular component code to be processed.
    Eg. @Component({ ... })
  class ExampleComponent {
    constructor() { }
  }
    `
  }

}, (a, b) => {
  return {
    name: "example-component",
    template: "<p>Example Component</p>",
    styles: ["p { color: red; }"]
  };
})

server.registerTool('service', {
  description: "This tool creates a Angular Service.",
})

server.registerTool('API', {
  description: "This tool creates a Angular API.",
})

server.registerTool('directive', {
  description: "This tool creates a Angular directive.",
})

server.registerTool('pipe', {
  description: "This tool creates a Angular pipe.",
})

server.registerTool('route', {
  description: "This tool creates a Angular route.",
})

let transport = null;

app.get("/sse", (req, res) => {
  transport = new SSEServerTransport("/messages", res);
  server.connect(transport);
});

app.post("/messages", (req, res) => {
  if (transport) {
    transport.handlePostMessage(req, res);
  }
});

app.listen(3000);